### PR TITLE
Ensure doorhanger closes when Launching a Website

### LINKED ISSUE #266: The "Lockwise" doorhanger is no longer dismissed after clicking the "Open Website" button
[Affected Versions]:
- Lockwise 2.2.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67 version installed.
- Have the Lockwise 2.2.1 - alpha extension installed.
- Have multiple saved logins.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockwise" toolbar button.
3. Click one of the saved logins from the doorhanger.
4. Click the "Open Website" button.
5. Observe the behavior.

[Expected results]:
- The Lockwise doorhanger is dismissed and the website is opened in a new tab.

[Actual results]:
- The Lockwise doorhanger is not dismissed and remains displayed after the website is opened in a new tab.

[Notes]:
- This issue is not reproducible with Lockwsie 2.2.0-alpha version.
- Attached a screen recording with the issue:
doorhanger not dismissed

### PR DESCRIPTION
**Pull request by linuxwolf**
Fixes #266

This change adds a `close` flag to the `openWebsite` action, which will close the popup if set to true.

## Testing and Review Notes

Follow the steps in #266

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)
- [x] make sure any new UI has telemetry events wired up and documented in docs/metrics.md, and verify that the events are recording properly (visit `about:telemetry#events-tab`, then choose 'dynamic' from the dropdown menu at top right, to view events fired by the addon

### CODE REVIEW

**Comment by meandavejustice** [comment]
```
WARNING in ./list/open-link-middleware.js 47:23-36
"export 'close' (imported as 'actions') was not found in './actions'
 @ ./list/manage/index.js
```

File: src/list/open-link-middleware.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ export default (store) => (next) => (action) => {
     break;
   case actions.OPEN_WEBSITE:
     const url = action.item.origins[0];
-    openWebsite(url, false);
+    openWebsite(url, actions.close);
```
Comment (meandavejustice) [inline src/list/open-link-middleware.js]: is this supposed to be `action.close`?

Comment (linuxwolf) [reply src/list/open-link-middleware.js]: d'oh!
