### PR TITLE
Correctly send telemetry after deleting an item

### LINKED ISSUE #200: The "itemDelete" telemetry ping is not sent after successfully delete an entry
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67 version installed.
- Have the Lockbox 2.1.0 - alpha extension installed.
- The "about:logins" page is opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click on the Lockbox toolbar button and click the "Open Lockbox" button.
3. Click on one of the saved logins from the list.
4. Click the "Delete" button from the top right part of the page.
5. Click the "Delete" button.
6. Navigate to "about:telemetry#events-tab" and select "dynamic" event and observe the last sent ping.

[Expected results]:
- The "itemDelete" telemetry ping is sent.

[Actual results]:
- The "itemDelete telemetry ping is not sent.

[Notes]:
- It seems that the "show - deleteConfirm" telemetry ping is sent when the "Delete this Entry" pop-up is displayed.
- Attached a screen recording with the issue:
itemDelete not sent

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #200.

## Testing and Review Notes

Usual telemetry testing steps apply:
- create and delete a login
- visit `about:telemetry#events-tab`, choose 'dynamic' from the dropdown menu at top right
- you should see an `itemDelete` in the list of events

If you want to verify that deletes outside the Lockwise UI do _not_ trigger the telemetry ping, you'll need to:
- create a login in the manage UI
- go to `about:config`
- clear out the contents of the `signon.management.overrideURI` pref
- go to `about:preferences` > Privacy & Security section > click 'Saved Logins' menu item
- delete the login from the built-in modal:

Screen Shot 2019-05-10 at 2 23 47 PM

- then go back to the `about:telemetry#events-tab` screen and verify that the `itemDelete` event was not fired.

## Screenshots or Videos

_(Optional: to clearly demonstrate the feature or fix to help with testing and reviews)_

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding integration tests
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-addon/developer/test-plan-accessibility/) of any added UI
- [x] make sure any new UI has telemetry events wired up and documented in docs/metrics.md, and verify that the events are recording properly (visit `about:telemetry#events-tab`, then choose 'dynamic' from the dropdown menu at top right, to view events fired by the addon

### CODE REVIEW

File: src/list/actions.js [hunk 1]
```diff
@@ -205,12 +205,12 @@ export function removeItem(id) {
...
     const actionId = nextActionId++;
     dispatch(removeItemStarting(actionId, id));
-
     await browser.runtime.sendMessage({
       type: "remove_item",
       id,
     });
-    dispatch(removeItemCompleted(actionId, id));
+    const interactive = true;
+    dispatch(removeItemCompleted(actionId, id, interactive));
```
Comment (linuxwolf) [inline src/list/actions.js]: nit: match the nearly identical calls from `updateItem()` by simply passing 'true` here.
