### PR TITLE
Strip Path from Website Address on Save

### LINKED ISSUE #236: The "duplicate login" error is wrongly displayed on the same row with the "Create New Login" title
[Notes]:
- On the [invisionapp mockups](https://mozilla.invisionapp.com/share/ENOL84959AK#/screens/338158452) and on older Lockwise versions the error was displayed above the title.

[Affected Versions]:
- Lockwise 2.2.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67 version installed.
- Have the Lockwise 2.1.0 - alpha extension installed.
- Have one saved login on a website.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockwise" toolbar button and click the "Open Lockwise" button from the doorhanger.
3. Click the "New Login" button.
4. Fill the "Website Address" and "Username" fields with the same data from the saved login from prerequisites.
5. Click the "Create Login" button.
6. Observe the "duplicate login" error position.

[Expected results]:
- The error is displayed above the "Create New Login" title.

[Actual results]:
- The error is displayed on the same row with the "Create New Login" title.

[Additional Notes]:
- The issue is also reproducible when trying to save an entry in edit mode with already used data.
- Attached a screenshot with the issue:
duplicate login

### LINKED ISSUE #238: Pasting a link into the "Website Address" field automatically adds a "/" and the saved login is not recognized on the website
[Affected Versions]:
- Lockwise 2.2.0-alpha
- Firefox 67.0b19

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- The Lockwise 2.2.0-alpha add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a website and copy the website's address. (e.g https://www.facebook.com)
3. Navigate to the Lockwise page and click the "New Login" button.
4. Paste the copied string into the "Website Address" field and fill the rest of the fields.
5. Save the login and launch it.
6. Observe the page.

[Expected results]:
- The website is displayed and the login is automatically filled.

[Actual results]:
- The saved login is not recognized by the website.

[Notes]:
- Pasting a link automatically adds a "/" at the end regardless of the used application.
- Attached a screen recording of the issue:
Extra_slash

### PR DESCRIPTION
**Pull request by linuxwolf**
Fixes #238
Fixes #236

The main patch coerces the `hostname` and `formSubmitURL` into an origin when adding a login.  This helps make manually-saved logins more reliable.

While open to there, corrected the "duplicate entry" error to be it's own row (again).

## Testing and Review Notes

Unit test added to verify behavior.

Perform steps from #238; the expected result should now be the login will work with autofill/autocomplete.

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
- [ ] request the "UX" team perform a design review (if/when applicable)
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

File: src/background/datastore.js [hunk 1]
```diff
@@ -91,6 +91,16 @@ export function convertItem2Info(item) {
   return info;
 }
 
+function extractOrigin(str) {
+  try {
+    const url = new URL(str);
+    return url.origin;
+  } catch (ex) {
+    // ignore failure  -- pretend it'll still save
```
Comment (6a68) [inline src/background/datastore.js]: Hm. If we ignore failure, it seems like the `(new URL(this.state.origin).hostname)` down below might also throw. Am I missing something?

Comment (linuxwolf) [reply src/background/datastore.js]: Oh, that's a good catch.  The only URLs I have seen throw are `chrome://` URLs, which _shouldn't_ make their way that far into the app, but they could.  I'll move this logic to a more generic helper.
